package com.platon.browser.dao.mapper;

import com.github.pagehelper.Page;
import com.platon.browser.dao.entity.Token721Inventory;
import com.platon.browser.dao.entity.TokenInventoryExample;
import com.platon.browser.dao.entity.Token721InventoryKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Token721InventoryMapper {

    long countByExample(TokenInventoryExample example);

    int deleteByExample(TokenInventoryExample example);

    int deleteByPrimaryKey(Token721InventoryKey key);

    int insert(Token721Inventory record);

    int insertSelective(Token721Inventory record);

    Page<Token721Inventory> selectByExample(TokenInventoryExample example);

    Token721Inventory selectByPrimaryKey(Token721InventoryKey key);

    int updateByExampleSelective(@Param("record") Token721Inventory record, @Param("example") TokenInventoryExample example);

    int updateByExample(@Param("record") Token721Inventory record, @Param("example") TokenInventoryExample example);

    int updateByPrimaryKeySelective(Token721Inventory record);

    int updateByPrimaryKey(Token721Inventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_inventory
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Token721Inventory> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table token_inventory
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Token721Inventory> list, @Param("selective") Token721Inventory.Column ... selective);
}